version: '3'

services:
  backend:
    image: ghufran1/auth:1.0.0
    command: sh ./entrypoint.sh
    ports:
      - "4000:4000"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgresdb
      POSTGRES_DATABASE: signupapp
    depends_on:
      - postgresdb
    
  frontend:
    image: ghufran1/web:1.0.0
    ports:
      - "80:80"
    

  postgresdb:
    image: postgres:latest
    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: signupapp
    ports:
      - "5432:5432"
    volumes:
      - backend-postgres-data:/var/lib/postgresql/data
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    

volumes:
  backend-postgres-data:
  


