version: '3'

services:
  backend:
    build: ./backend/auth
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      POSTGRES_USERNAME: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_HOST: postgresdb
      POSTGRES_DATABASE: $AUTH_DB
    depends_on:
      - postgresdb
    command: /app/entrypoint.sh 
    

  frontend:
    build: ./web
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"

  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $AUTH_DB
    ports:
      - "5432:5432"
    volumes:
      - backend-postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"   

volumes:
  backend-postgres-data: